#!/usr/bin/perl
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;

use strict;
use warnings;

use Test::More;
$TODO = q{Mouse is not yet completed};

# if make_immutable is removed from the following code the tests pass

{
    package Foo;
    use Mouse;

    has foo => ( is => "ro" );

    package Bar;
    use Mouse;

    extends qw(Foo);

    around new => sub {
        my $next = shift;
        my ( $self, @args ) = @_;
        $self->$next( foo => 42 );
    };

    package Gorch;
    use Mouse;

    extends qw(Bar);

    package Zoink;
    use Mouse;

    extends qw(Gorch);

}

my @classes = qw(Foo Bar Gorch Zoink);

tests: {
 TODO: {
    is( Foo->new->foo, undef, "base class (" . (Foo->meta->is_immutable ? "immutable" : "mutable") . ")" );
    is( Bar->new->foo, 42, "around new called on Bar->new (" . (Bar->meta->is_immutable ? "immutable" : "mutable") . ")"  );
    is( Gorch->new->foo, 42, "around new called on Gorch->new (" . (Gorch->meta->is_immutable ? "immutable" : "mutable") . ")"  );
    is( Zoink->new->foo, 42, "around new called Zoink->new (" . (Zoink->meta->is_immutable ? "immutable" : "mutable") . ")"  );
    }

    if ( @classes ) {
        local $SIG{__WARN__} = sub {};
        ( shift @classes )->meta->make_immutable;
        redo tests;
    }
}

done_testing;
