#!/usr/bin/env perl
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;
use strict;
use warnings;
use Test::More;
use Test::Exception;

{
    package Foo::API;
    use Mouse::Role;

    requires 'foo';
}

{
    package Foo;
    use Mouse::Role;

    has foo => (is => 'ro');

    with 'Foo::API';
}

{
    package Foo::Class;
    use Mouse;
    { our $TODO; local $TODO = "role accessors don't satisfy other role requires";
    ::lives_ok { with 'Foo' } 'requirements are satisfied properly';
    }
}

{
    package Bar;
    use Mouse::Role;

    requires 'baz';

    has bar => (is => 'ro');
}

{
    package Baz;
    use Mouse::Role;

    requires 'bar';

    has baz => (is => 'ro');
}

{
    package BarBaz;
    use Mouse;

    { our $TODO; local $TODO = "role accessors don't satisfy other role requires";
    ::lives_ok { with qw(Bar Baz) } 'requirements are satisfied properly';
    }
}

done_testing;
