use strict;
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;
use warnings;
use Test::More;

{
    package Foo;
    use Mouse::Role;

    use overload
        q{""}    => sub { 42 },
        fallback => 1;

    no Mouse::Role;
}

{
    package Bar;
    use Mouse;
    with 'Foo';
    no Mouse;
}

my $bar = Bar->new;

TODO: {
    local $TODO = "the special () method isn't properly composed into the class";
    is("$bar", 42, 'overloading can be composed');
}

done_testing;
