use strict;
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;
use warnings;
use Test::More;
$TODO = q{Mouse is not yet completed};

{
    package FooBar;
    use Mouse;

    has 'name' => ( is => 'ro' );

    sub DESTROY { shift->name }

    local $SIG{__WARN__} = sub {};
    __PACKAGE__->meta->make_immutable;
}

my $f = FooBar->new( name => 'SUSAN' );

is( $f->DESTROY, 'SUSAN', 'Did moose overload DESTROY?' );

done_testing;
