use strict;
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;
use warnings;

use Test::More;
use Test::Exception;

use Mouse::Meta::Class;

$SIG{__WARN__} = sub { die if shift =~ /recurs/ };

TODO:
{
    local $TODO
        = 'Loading Mouse::Meta::Class without loading Mouse.pm causes weird problems';

    my $meta;
    lives_ok {
        $meta = Mouse::Meta::Class->create_anon_class(
            superclasses => [ 'Mouse::Object', ],
        );
    }
    'Class is created successfully';
}

done_testing;
