#!/usr/bin/perl
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;

use strict;
use warnings;

use Test::More;
use Test::Exception;

{
    package Foo;
    use Mouse;

    has 'bar' => ( is => 'rw' );

    package Stuffed::Role;
    use Mouse::Role;

    has 'options' => (
        traits => ['Array'],
        is     => 'ro',
        isa    => 'ArrayRef[Foo]',
    );

    package Bulkie::Role;
    use Mouse::Role;

    has 'stuff' => (
        traits  => ['Array'],
        is      => 'ro',
        isa     => 'ArrayRef',
        handles => {
            get_stuff => 'get',
        }
    );

    package Stuff;
    use Mouse;

    ::lives_ok{ with 'Stuffed::Role';
        } '... this should work correctly';

    ::lives_ok{ with 'Bulkie::Role';
        } '... this should work correctly';
}

done_testing;
