#!/usr/bin/perl
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;

use strict;
use warnings;

use Test::More;
$TODO = q{Mouse is not yet completed};
use Test::Exception;


BEGIN {
    package MyFramework::Base;
    use Mouse;

    package MyFramework::Meta::Base;
    use Mouse;

    extends 'Mouse::Meta::Class';

    package MyFramework;
    use Mouse;
    use Mouse::Deprecated -api_version => '0.55';

    sub import {
        my $CALLER = caller();

        strict->import;
        warnings->import;

        return if $CALLER eq 'main';
        Mouse::init_meta( $CALLER, 'MyFramework::Base', 'MyFramework::Meta::Base' );
        Mouse->import({ into => $CALLER });

        return 1;
    }
}

{
    package MyClass;
    BEGIN { MyFramework->import }

    has 'foo' => (is => 'rw');
}

can_ok( 'MyClass', 'meta' );

isa_ok(MyClass->meta, 'MyFramework::Meta::Base');
isa_ok(MyClass->meta, 'Mouse::Meta::Class');

my $obj = MyClass->new(foo => 10);
isa_ok($obj, 'MyClass');
isa_ok($obj, 'MyFramework::Base');
isa_ok($obj, 'Mouse::Object');

is($obj->foo, 10, '... got the right value');

done_testing;
