use strict;
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;
use warnings;

use Test::More;
$TODO = q{Mouse is not yet completed};

{
    package Foo::Role;
    use Mouse::Role;
}

{
    package Bar::Role;
    use Mouse::Role;
}

{
    package Foo;
    use Mouse;
    with 'Foo::Role';
}

{
    package Bar;
    use Mouse;
    extends 'Foo';
    with 'Bar::Role';
}

{
    package FooBar;
    use Mouse;
    with 'Foo::Role', 'Bar::Role';
}

{
    package Foo::Role::User;
    use Mouse::Role;
    with 'Foo::Role';
}

{
    package Foo::User;
    use Mouse;
    with 'Foo::Role::User';
}

is_deeply([sort Foo::Role->meta->consumers],
          ['Bar', 'Foo', 'Foo::Role::User', 'Foo::User', 'FooBar']);
is_deeply([sort Bar::Role->meta->consumers],
          ['Bar', 'FooBar']);
is_deeply([sort Foo::Role::User->meta->consumers],
          ['Foo::User']);

done_testing;
