#!/usr/bin/env perl
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;
use strict;
use warnings;
use Test::More;
$TODO = q{Mouse is not yet completed};

do {
    package My::Meta::Role;
    use Mouse;
    BEGIN { extends 'Mouse::Meta::Role' };
};

do {
    package My::Role;
    use Mouse::Role -metaclass => 'My::Meta::Role';
};

is(My::Role->meta->meta->name, 'My::Meta::Role');

done_testing;
