use strict;
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;
use warnings;

use Test::More;
$TODO = q{Mouse is not yet completed};
use Test::Exception;

{
    package My::Role1;
    use Mouse::Role;

    has foo => (
        is => 'ro',
    );

}

{
    package My::Role2;
    use Mouse::Role;

    has foo => (
        is => 'ro',
    );

    ::throws_ok { with 'My::Role1' } qr/attribute conflict.+My::Role2.+foo/,
        'attribute conflict when composing one role into another';
}

done_testing;
