use strict;
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;
use warnings;

use Test::More;
$TODO = q{Mouse is not yet completed};

use Test::Requires {
    'Test::Output' => '0.01', # skip all if not installed
};

{
    package Foo;

    use Mouse;

    ::stderr_like{ has foo => (
            is     => 'ro',
            isa    => 'Str',
            coerce => 1,
        );
        }
        qr/\QYou cannot coerce an attribute (foo) unless its type (Str) has a coercion/,
        'Cannot coerce unless the type has a coercion';

    ::stderr_like{ has bar => (
            is     => 'ro',
            isa    => 'Str',
            coerce => 1,
        );
        }
        qr/\QYou cannot coerce an attribute (bar) unless its type (Str) has a coercion/,
        'Cannot coerce unless the type has a coercion - different attribute';
}

done_testing;
