
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;
package Foo;
use Mouse;

has 'bar' => (is => 'rw');

1;