package MyMouseObject;
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use MooseCompat;

use strict;
use warnings;
use base 'Mouse::Object';

1;