package MyMooseA;
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;

use Mouse;

has 'b' => (is => 'rw', isa => 'MyMooseB');

1;