#!/usr/bin/perl
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;

use strict;
use warnings;

use Test::More;
$TODO = q{Mouse is not yet completed};
use Mouse ();

BEGIN {
    use_ok('Mouse::Meta::Attribute::Native');
    use_ok('Mouse::Meta::Attribute::Native::Trait::Bool');
    use_ok('Mouse::Meta::Attribute::Native::Trait::Hash');
    use_ok('Mouse::Meta::Attribute::Native::Trait::Array');
    use_ok('Mouse::Meta::Attribute::Native::Trait::Counter');
    use_ok('Mouse::Meta::Attribute::Native::Trait::Number');
    use_ok('Mouse::Meta::Attribute::Native::Trait::String');
}

done_testing;
