#!/usr/bin/perl
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;

use strict;
use warnings;

use Test::More;

{
    package Foo;

    # Mouse will issue a warning if we try to load it from the main
    # package.
    ::use_ok('Mouse');
}

done_testing;
