#!/usr/bin/perl
# This is automatically generated by author/import-moose-test.pl.
# DO NOT EDIT THIS FILE. ANY CHANGES WILL BE LOST!!!
use t::lib::MooseCompat;

use strict;
use warnings;

use Test::More;
use Test::Exception;

lives_ok {
    eval 'use Mouse';
} "export to main";

isa_ok( main->meta, "Mouse::Meta::Class" );

isa_ok( main->new, "main");
isa_ok( main->new, "Mouse::Object" );

done_testing;
